# Generated by Django 5.2.12 on 2026-03-30 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordens_servico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='gerente_aprovador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_aprovadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tecnico_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempeca',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens_servico.ordemservico'),
        ),
    ]
