# Generated by Django 5.2.12 on 2026-05-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens_servico', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada'), ('paga', 'Paga')], default='aberta', max_length=20),
        ),
    ]
