# Generated by Django 5.2.12 on 2026-03-30 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desktop', 'Desktop'), ('notebook', 'Notebook'), ('servidor', 'Servidor'), ('all_in_one', 'All in One')], max_length=20)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('patrimonio', models.CharField(blank=True, max_length=50)),
                ('nome_identificacao', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('processador', models.CharField(max_length=200)),
                ('memoria_ram', models.CharField(max_length=50)),
                ('armazenamento', models.CharField(max_length=200)),
                ('sistema_operacional', models.CharField(max_length=100)),
                ('possui_monitor', models.BooleanField(default=False)),
                ('possui_teclado', models.BooleanField(default=False)),
                ('possui_mouse', models.BooleanField(default=False)),
                ('observacoes_hardware', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ativo', 'Em Uso'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção'), ('baixado', 'Baixado')], default='ativo', max_length=20)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_manutencao', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
                'ordering': ['cliente', 'nome_identificacao'],
            },
        ),
    ]
